import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { UserProvider } from "./context/UserContext";
import AuthRedirect from "./AuthRedirect";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-gradient-to-br from-[#EDE8D0] via-white to-[#F6F1E6] antialiased min-h-screen`}
      >
        <UserProvider>
          <AuthRedirect />
          <Navbar />

          <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div
              className="bg-white/60 backdrop-blur-md rounded-2xl shadow-lg border border-white/30 overflow-hidden animate-fade-in"
              style={{ animationDuration: "300ms" }}
            >
              {children}
            </div>
          </main>
        </UserProvider>
      </body>
    </html>
  );
}
